export default {
  // Common
  Register: 'تسجيل',
  loginTitle: 'يا هلا بك',
  Login: 'تسجيل دخول',
  enter: 'دخول',
  forgetPass: 'نسيت كلمة المرور؟',
  dontHaveAccount: 'ليس لديك حساب؟',
  createNew: ' انشاء جديد',
  password: 'كلمة المرور',
  confirmPassword: 'تأكيد كلمة المرور',
  loginWithEmail: 'الدخول بالإيميل؟',
  loginWithMobile: 'الدخول برقم الجوال؟',
  continue: 'متابعة',
  email: 'البريد الإلكتروني',
  termsOfUse: 'شروط الإستخدام',
  send: 'ارسال',
  phoneNumber: 'رقم الجوال',
  currentPass: 'كلمة المرور الحالية',
  newPass: 'كلمة المرور الجديدة',
  confirmNewPass: 'تأكيد كلمة المرور الجديدة',
  favorites: 'المفضلة',
  cancel: 'إلغاء',
  providerLogin: 'دخول مقدم الخدمة',
  addYourData: 'اضف بياناتك للدخول',
  enterPhone: 'ادخل رقم جوالك وسيصلك رمز التحقق لتتمكن من إعادة تعيين كلمة المرور',
  activationCode: 'رمز التحقق',
  enterCode: 'ادخل رمز التحقق المرسل على جوالك',
  enterCodeEmail: 'ادخل رمز التحقق المرسل على ايميلك',
  didntGetCode: 'لم يصلك رمز التفعيل؟ ',
  resend: 'إعادة الإرسال',
  resendAfter: 'إعادة الإرسال بعد',
  resetPass: 'إعادة تعيين كلمة المرور',
  addPass: 'قم بإضافة كلمة المرور الجديدة مرتين للمتابعة',
  reset: 'إعادة تعيين',
  createAccount: 'انشاء حساب جديد',
  subScribeAnd: 'اشترك واعرض قاربك أو يختك الخاص بك للإيجار',
  fullName: 'الاسم بالكامل',
  IdNumber: 'رقم الهوية',
  yourRegisterMean: 'تسجيلك بالتطبيق يعني موافقتك على',
  hasAccount: 'لديك حساب؟',
  loginNow: 'سجل دخول',
  noBoatsAdded: 'ليس لديك أي قوارب مضافة',
  addNewBoat: 'اضف قارب جديد',
  allRight: '© جميع الحقوق محفوظة {{year}}',
  backToHome: 'الرجوع إلى الرئيسية',
  addBoatRequestSent: 'تم ارسال طلب إضافة قارب',
  sarPerDay: 'ر.س/ الساعة',
  hasBooked: 'تم حجزه {{number}} مرة',
  havePrblem: ' لديك مشكلة؟ ',
  contactUs: 'اتصل بنا',
  addingNewBoat: 'إضافة قارب جديد',
  enjoyUrTrip: 'اشترك واستمتع برحلتك البحرية بالمملكة',
  boatName: 'اسم القارب',
  boatType: 'نوع القارب',
  boatLicense: 'ترخيص القارب',
  boatImages: 'صور القارب',
  boatPrice: 'سعر القارب/ الساعة',
  description: 'الوصف',
  add: 'اضافة',
  priceInSAR: 'السعر بالريال السعودي',
  addDecription: 'اضف وصف تفصيلي عن القارب',
  boatWidth: 'عرض القارب',
  unitOfMeasure: 'وحدة القياس/ القدم',
  membersNum: 'عدد الأفراد',
  personsNum: 'عدد الأشخاص',
  numberofCabins: 'عدد الكبائن',
  numberOfBathrooms: 'عدد الحمامات',
  rentalTerms: 'شروط الإيجار',
  cancellationTerms: 'شروط الإلغاء',
  approximateLocation: 'الموقع التقريبي',
  locationWillBeSent: 'سيتم ارسال الموقع التفصيلي للمغادرة عند القيام بالحجز',
  addLocation: 'اضف موقع تقريبي وفقا للشروط',
  savingChanges: 'حفظ التغييرات',
  availableDays: 'الأيام المتاحة',
  availableTimes: 'الأوقات المتاحة',
  reservations: 'حجوزاتي',
  newBooking: 'حجز معلق',
  previousBooking: 'حجز مقبول',
  canceledBooking: 'حجز مرفوض',
  new: 'معلق',
  done: 'مقبول',
  canceled: 'مرفوض',
  from: 'من',
  to: 'إلى',
  person: 'شخص',
  accept: 'قبول',
  reject: 'رفض',
  showDetails: 'عرض التفاصيل',
  bookingDetails: 'تفاصيل الحجز',
  bookingStatus: 'حالة الطلب',
  bookingNum: 'رقم الحجز',
  driver: 'ربان القيادة',
  paymentMethod: 'طريقة الدفع',
  successBooking: 'حجوزات ناجحة',
  vat: 'ضريبة القيمة المضافة',
  sailingCost: 'تكلفة إيجار {{daysNum}} أيام',
  totalDue: 'الإجمالي المستحق',
  chatWithCleint: 'دردشة مع العميل',
  rateCleint: 'تقييم العميل',
  addUrRate: 'اضف تقييمك للعميل',
  addUrRateDescription: 'اضف وصف تقييك للعميل',
  message: 'الرسالة',
  online: 'متصل',
  offline: 'غير متصل',
  typing: 'يكتب ...',
  hello: 'هلا',
  editProfile: 'تعديل الملف الشخصي',
  aboutApp: 'عن التطبيق',
  language: 'اللغة',
  shareApp: 'شارك التطبيق مع أصدقائك',
  rateApp: 'اضف تقييمك للتطبيق',
  logout: 'تسجيل خروج',
  editProfileData: 'تعديل بيانات الحساب',
  changePassword: 'تغيير كلمة المرور',
  addImage: 'إضافة صورة',
  supportTeamIsReady: 'فريق الدعم جاهز لمساعدتك',
  sendUs: 'ارسل لنا استفسارك او اقتراحك وسيتم التواصل معك في أقرب وقت ممكن',
  messageContent: 'نص الرسالة',
  myBoats: 'قواربي',
  myMessages: 'رسائلي',
  myReservations: 'حجوزاتى',
  myAccount: 'حسابي',
  startNow: 'ابدأ الآن',
  skip: 'تخطى البداية',
  owner: 'المالك',
  cancelConds: 'شروط الإلغاء',
  locationOnMap: 'الموقع على الخريطة',
  chatWithOwner: 'دردشة مع المالك',
  rateExperince: 'تقييم التجربة',
  browseBoats: 'استكشف القوارب',
  exploreDestinationsKingdom: 'استكشف الوجهات بالمملكة',
  searchByDestination: 'ابحث باسم وجهتك؟',
  explore: 'استكشف',
  nearToYou: 'الأقرب إليك',
  orWeSuggest: 'أو نقترح عليك',
  resultsOfSearch: 'نتائج البحث {{number}} قارب',
  filterSearch: 'فلترة البحث',
  Reset: 'استعادة',
  pricePerDay: 'السعر/ لليوم',
  Additions: 'اضافات',
  displayResults: 'عرض النتائج',
  equipmentAndAdvantages: 'المعدات والمزايا',
  services: 'الخدمات',
  ratingsNum: 'التقييمات ({{number}})',
  browseAvailableDays: 'استعرض الأيام المتاحة',
  mustBeLoggedIn: 'يجب تسجيل الدخول',
  toAccessThisPage: 'للدخول الى هذه الصفحة يجب تسجيل الدخول',
  bookingDate: 'تاريخ الحجز',
  bookMoreThanDay: 'حجز أكثر من يوم',
  recovery: 'استعادة',
  bookingStartDate: 'تاريخ بداية الحجز',
  bookingEndDate: 'تاريخ نهاية الحجز',
  completeBooking: 'استكمال الحجز',
  optionalServices: 'خدمات اختيارية',
  edit: 'تعديل',
  confirmAndPay: 'تأكيد الحجز والدفع',
  payNow: 'ادفع الآن',
  bookingConfirmedSuccessfully: 'تم تأكيد الحجز بنجاح',
  uCanReviewDetails: 'يمكنك مراجعة تفاصيل الحجز رقم {{number}} من خلال صفحة',
};
